language: erlang
script: "make compile test"
install: "sudo pip install codecov"
after_success: "codecov"
dist: trusty
otp_release:
- 19.3
- 20.0
- 20.1
- 20.2
- 20.3
- 21.0
- 21.1
- 21.2
- 21.3
- 22.0
- 22.1
- 22.2
notifications:
  slack:
    secure: R/DFvrTxdCqOtfQ9Fp9x21Dsd74nltDk98LR8Gq/hydJIR8IC6I62b8XLje74YFb0yjtXc6v3AIrZAu8WuLDn6fij+yGV0nRy4z3pZA2Sq9qN1QEZ2MYpRJWy36ZU4qf/ST3ZcUArIQr7hGslpSEJy7f6PhKajcU/5p97Ps3k2s=
